/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 327d2849d96b8194e546172632d7be48)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "AuditAgent";
	}
	interface Env {
		AI: Ai;
		AuditAgent: DurableObjectNamespace<import("./src/server").AuditAgent>;
		WEBSITE_AUDIT_WORKFLOW: Workflow<Parameters<import("./src/server").WebsiteAuditWorkflow['run']>[0]['payload']>;
	}
}
interface Env extends Cloudflare.Env {}
